---
- name: Configure the bind interface
  copy:
    content: "{{ hostvars[inventory_hostname]['ansible_' + bind_interface].ipv4.address }}"
    dest: /etc/mesos-slave/ip
  notify: restart mesos-slave

- name: Configure the containerizers
  copy:
    content: "docker,mesos"
    dest: /etc/mesos-slave/containerizers
  notify: restart mesos-slave

- name: Configure the container startup time
  copy:
    content: "10mins"
    dest: /etc/mesos-slave/executor_registration_timeout
  notify: restart mesos-slave

- name: Disable Mesos Master
  service: name=mesos-master state=stopped enabled=no

- name: Enable Mesos Slave
  service: name=mesos-slave state=started enabled=yes

